version: "3.8"

services:

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "6666:5432"
    restart: unless-stopped

  app:
    container_name: app
    build: .
    volumes:
      - ./logs:/logs
      - ./secrets:/secrets
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pg-data:
